short_name: truthtable
namespace: qpy
version: 0.1.0
api_version: '0.1'
author: innoCampus <info@isis.tu-berlin.de>
name:
  de: Wahrheitstabellen
  en: Truth Tables
languages:
  - de
  - en
requirements:
  - antlr4-python3-runtime
  - sympy
build_hooks:
  pre:
    - npm --prefix $QPY_SOURCE/ts ci
    - npm --prefix $QPY_SOURCE/ts run build
